
name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (optional, if you have npm/yarn builds)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Add frontend build commands here if needed
      # - name: Install dependencies and build frontend
      #   run: |
      #     cd frontend
      #     npm install
      #     npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
